<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="11037-chart-with-upwards-trend.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="11037-chart-with-upwards-trend.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YahooFinanceApi" Version="2.3.3" />
  </ItemGroup>

</Project>
